-- Campus Trade Database Schema
-- Import this file directly in phpMyAdmin after creating the 'aiub_campus_trade' database

CREATE TABLE users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(20),
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  profile_pic VARCHAR(255),
  role ENUM('admin','student') DEFAULT 'student',
  status ENUM('active','blocked') DEFAULT 'active',
  reset_token VARCHAR(64) NULL,
  reset_expires DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  category_id INT AUTO_INCREMENT PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL
);

CREATE TABLE products (
  product_id INT AUTO_INCREMENT PRIMARY KEY,
  seller_id INT,
  category_id INT,
  title VARCHAR(150) NOT NULL,
  description TEXT,
  price DECIMAL(10,2),
  item_condition ENUM('new','used'),
  listing_type ENUM('sell','rent'),
  image VARCHAR(255),
  status ENUM('available','sold','removed') DEFAULT 'available',
  posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES users(user_id),
  FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

CREATE TABLE requests (
  request_id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT,
  buyer_id INT,
  status ENUM('pending','accepted','rejected','completed') DEFAULT 'pending',
  meetup_location VARCHAR(150),
  meetup_time DATETIME,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(product_id),
  FOREIGN KEY (buyer_id) REFERENCES users(user_id)
);

CREATE TABLE messages (
  message_id INT AUTO_INCREMENT PRIMARY KEY,
  sender_id INT,
  receiver_id INT,
  product_id INT,
  message_text TEXT,
  sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sender_id) REFERENCES users(user_id),
  FOREIGN KEY (receiver_id) REFERENCES users(user_id)
);

CREATE TABLE reviews (
  review_id INT AUTO_INCREMENT PRIMARY KEY,
  reviewer_id INT,
  reviewed_user_id INT,
  request_id INT NULL,
  rating INT CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reviewer_id) REFERENCES users(user_id),
  FOREIGN KEY (reviewed_user_id) REFERENCES users(user_id),
  FOREIGN KEY (request_id) REFERENCES requests(request_id)
);

CREATE TABLE wishlist (
  wishlist_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  product_id INT,
  FOREIGN KEY (user_id) REFERENCES users(user_id),
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE reports (
  report_id INT AUTO_INCREMENT PRIMARY KEY,
  reporter_id INT,
  product_id INT,
  reason TEXT,
  status ENUM('pending','reviewed') DEFAULT 'pending',
  reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (reporter_id) REFERENCES users(user_id),
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- A default category list to start with (optional but useful for testing)
INSERT INTO categories (category_name) VALUES
('Books'), ('Electronics'), ('Furniture'), ('Cycles'), ('Others');

-- NOTE on creating an admin account:
-- Don't insert an admin row here with a guessed password hash — hashes must be generated by PHP's
-- password_hash() so they match exactly. Instead: register a normal account through register.php,
-- then come back to phpMyAdmin, open the users table, and change that row's `role` from
-- 'student' to 'admin'. That account will then log in as admin with the password you set.
